FROM publicisworldwide/python-conda:latest

LABEL author="Kersten Breuer, Zeller Team, EMBL 2019" \
    maintainer="kersten-breuer@outlook.com"

# Package versions/links:
ENV BWMETH_VERSION "0.2.2"

# Install:
RUN conda install bwameth