FROM ubuntu:18.04

LABEL author="Kersten Breuer, Cancer Epigenomics, Plass Team, DKFZ 2019" \
    maintainer="kersten-breuer@outlook.com"

RUN apt-get -y update --fix-missing -qq
RUN apt-get -y install \
    build-essential \
    checkinstall \
    wget \
    unzip \
    libtbb-dev \
    libxml2 libxml2-dev \
    r-base-dev \
    libncursesw5-dev \
    libssl-dev \
    libsqlite3-dev \
    tk-dev \
    libgdbm-dev \
    libc6-dev \
    libbz2-dev \
    openjdk-8-jdk \
    libboost-all-dev \
    tar \
    cmake \
    zlib1g-dev \
    bzip2 \
    libghc-bzlib-dev \
    zlib1g-dev \
    liblzma-dev \
    libncurses5-dev \
    imagemagick \
    gawk \
    python-setuptools \
    python-rpy2 \
    python-dev \
    python-pip \
    python3-dev \
    python3-pip \
    gcc-multilib gcc \
    apt-utils \
    vim-common \
    libbam-dev \
    software-properties-common \
    default-jre \
    unzip \
    glib-networking-common
